# Generated by Django 3.2.16 on 2022-11-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connect_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='192.168.0.1', max_length=32, verbose_name='链接')),
                ('status', models.CharField(default='false', max_length=32, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.CharField(max_length=32, verbose_name='时间')),
                ('operation', models.CharField(max_length=32, verbose_name='操作')),
                ('url', models.CharField(max_length=32, verbose_name='服务链接')),
                ('content', models.CharField(max_length=32, verbose_name='上下文')),
            ],
        ),
        migrations.CreateModel(
            name='read_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32, verbose_name='服务链接')),
                ('nodeid', models.CharField(max_length=32, verbose_name='名称')),
                ('timestamps', models.CharField(max_length=32, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='write_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32, verbose_name='服务链接')),
                ('nodeid', models.CharField(max_length=32, verbose_name='名称')),
                ('value', models.CharField(max_length=32, verbose_name='写入值')),
                ('timestamps', models.CharField(max_length=32, verbose_name='时间')),
            ],
        ),
    ]
