# Generated by Django 3.2.16 on 2022-11-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect_temp',
            name='status',
            field=models.CharField(max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='connect_temp',
            name='url',
            field=models.CharField(max_length=32, verbose_name='链接'),
        ),
    ]
