# Generated by Django 3.2.16 on 2022-12-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0003_auto_20221211_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='server_log',
            name='value',
            field=models.CharField(default=1, max_length=32, verbose_name='数值'),
            preserve_default=False,
        ),
    ]
