# Generated by Django 3.2.16 on 2022-12-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0004_server_log_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server_log',
            name='content',
        ),
    ]
