# Generated by Django 3.2.16 on 2022-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0005_remove_server_log_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_log',
            name='nodeid',
            field=models.CharField(max_length=255, verbose_name='节点名称'),
        ),
        migrations.AlterField(
            model_name='server_log',
            name='operation',
            field=models.CharField(max_length=255, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='server_log',
            name='timestamps',
            field=models.CharField(max_length=255, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='server_log',
            name='url',
            field=models.CharField(max_length=255, verbose_name='服务链接'),
        ),
        migrations.AlterField(
            model_name='server_log',
            name='value',
            field=models.CharField(max_length=255, verbose_name='数值'),
        ),
    ]
