# Generated by Django 3.2.16 on 2022-12-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0010_auto_20221214_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='opcua_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='服务链接')),
                ('nodeid', models.CharField(max_length=255, verbose_name='节点名称')),
                ('operation', models.CharField(max_length=255, verbose_name='操作')),
                ('timestamps', models.CharField(max_length=255, verbose_name='操作时间')),
                ('value', models.CharField(max_length=255, verbose_name='数值')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
            ],
        ),
    ]
