# Generated by Django 3.2.16 on 2022-12-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0002_auto_20221126_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='server_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=32, verbose_name='服务链接')),
                ('nodeid', models.CharField(max_length=64, verbose_name='节点名称')),
                ('operation', models.CharField(max_length=32, verbose_name='操作')),
                ('content', models.CharField(max_length=32, verbose_name='上下文')),
                ('timestamps', models.CharField(max_length=32, verbose_name='操作时间')),
            ],
        ),
        migrations.DeleteModel(
            name='connect_temp',
        ),
        migrations.DeleteModel(
            name='log',
        ),
        migrations.DeleteModel(
            name='read_temp',
        ),
        migrations.DeleteModel(
            name='write_temp',
        ),
    ]
