# Generated by Django 3.2.16 on 2022-12-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0007_opcua_server'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='opcua_server',
            new_name='opcua_servermsg',
        ),
    ]
