# Generated by Django 3.2.16 on 2022-12-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0008_rename_opcua_server_opcua_servermsg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='opcua_servermsg',
            new_name='OPCUA_server',
        ),
    ]
