# Generated by Django 3.2.16 on 2022-12-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0009_rename_opcua_servermsg_opcua_server'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OPCUA_server',
            new_name='opcuaserver',
        ),
        migrations.RenameField(
            model_name='opcuaserver',
            old_name='nodeid',
            new_name='node_id',
        ),
        migrations.RenameField(
            model_name='opcuaserver',
            old_name='nodename',
            new_name='node_name',
        ),
        migrations.RenameField(
            model_name='opcuaserver',
            old_name='nodevalue',
            new_name='node_value',
        ),
    ]
