# Generated by Django 3.2.16 on 2022-12-14 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcuaTest', '0011_opcua_change'),
    ]

    operations = [
        migrations.DeleteModel(
            name='opcua_change',
        ),
    ]
